#!/bin/bash
if [ $# -eq 2 ]
	 then
	echo "Suma: `expr $1 + $2`"
	echo "Resta: `expr $1 - $2`"
	echo "Multiplicacion: `expr $1 \* $2`"
	if [ $1 -gt $2 ]
	then
		echo "$1 es mayor que $2"
	elif [ $1 -lt $2 ]
	then
		echo "$2 es mayor que $1"
	else
		echo "Son iguales"
	fi
fi
