#!/bin/bash
select opcion in Listar DondeEstoy QuienEsta
do
	case $opcion in
	"Listar")
	echo $(ls); exit 0
	;;
	"DondeEstoy")
	echo $(pwd); exit 0
	;;
	"QuienEsta")
	echo $(who); exit 0
	;;
	esac
done
